const languages = new Map([
  ["Afrikaans",	          new Map([["lang_code", "af_ZA"],
                                   ["utf8", ".UTF-8"],
			           ["none_utf8", ""]])],
  ["Arabic",     	  new Map([["lang_code", "ar_EG"],
  		                   ["utf8", ".UTF-8"],
			           ["none_utf8", ""]])],
  ["Asturian",   	  new Map([["lang_code", "ast_ES"],
  		                   ["utf8", ".UTF-8"],
			           ["none_utf8", "@euro"]])],
  ["Bengali",    	  new Map([["lang_code", "bn_BD"],
  		                   ["utf8", ".UTF-8"],
			           ["none_utf8", ""]])],
  ["Bosnian",    	  new Map([["lang_code", "bs_BA"],
  		                   ["utf8", ".UTF-8"],
			           ["none_utf8", ""]])],
  ["Bulgarian",  	  new Map([["lang_code", "bg_BG"],
  		                   ["utf8", ".UTF-8"],
			           ["none_utf8", ""]])],
  ["Catalan",    	  new Map([["lang_code", "ca_ES"],
  		     	           ["utf8", ".UTF-8"],
			      	   ["none_utf8", "@euro"]])],
  ["Chinese Simplified",  new Map([["lang_code", "zh_CN"],
  	    		           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Chinese Traditional", new Map([["lang_code", "zh_TW"],
  	    		           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Croatian", 	          new Map([["lang_code", "hr_HR"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Czech", 	          new Map([["lang_code", "cs_CZ"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Danish", 	          new Map([["lang_code", "da_DK"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Dutch",               new Map([["lang_code", "nl_NL"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", "@euro"]])],
  ["English (UK)",        new Map([["lang_code", "en_GB"],
  	    		           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["English (US)",        new Map([["lang_code", "en_US"],
  	    		           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Estonian",            new Map([["lang_code", "et_EE"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Finnish", 		  new Map([["lang_code", "fi_FI"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", "@euro"]])],
  ["French",              new Map([["lang_code", "fr_FR"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", "@euro"]])],
  ["Galician",            new Map([["lang_code", "gl_ES"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", "@euro"]])],
  ["Georgian",            new Map([["lang_code", "ka_GE"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["German", 	          new Map([["lang_code", "de_DE"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", "@euro"]])],
  ["Greek",               new Map([["lang_code", "el_GR"],
                                   ["utf8", ".UTF-8"],
                                   ["none_utf8", ".ISO-8859-7"]])],
  ["Gujarati",            new Map([["lang_code", "gu_IN"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Hebrew",              new Map([["lang_code", "he_IL"],
  			           ["utf8", ".UTF-8"],
                                   ["none_utf8", ""]])],
  ["Hindi",               new Map([["lang_code", "hi_IN"],
                                   ["utf8", ".UTF-8"],
                                   ["none_utf8", ""]])],
  ["Hungarian",           new Map([["lang_code", "hu_HU"],
                                   ["utf8", ".UTF-8"],
                                   ["none_utf8", ""]])],
  ["Indonesian",          new Map([["lang_code", "id_ID"],
                                   ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Italian",             new Map([["lang_code", "it_IT"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", "@euro"]])],
  ["Japanese", 	          new Map([["lang_code", "ja_JP"],
                                   ["utf8", ".UTF-8"],
                                   ["none_utf8", ".eucJP"]])],
  ["Khmer",               new Map([["lang_code", "km_KH"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Korean",              new Map([["lang_code", "ko_KR"],
  			           ["utf8", ".UTF-8"],
                                   ["none_utf8", ""]])],
  ["Lithuanian",          new Map([["lang_code", "lt_LT"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Macedonian",          new Map([["lang_code", "mk_MK"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Marathi",             new Map([["lang_code", "",],
  			           ["utf8", ".UTF-8"],
   				   ["none_utf8", ""]])],
  ["Norwegian",           new Map([["lang_code", "nb_NO"],
  			           ["utf8", ".UTF-8"],
  				   ["none_utf8", ""]])],
  ["Nynorsk", 	          new Map([["lang_code", "nn_NO"],
                                   ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Persian",             new Map([["lang_code", "fa_IR"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Polish", 		  new Map([["lang_code", "pl_PL"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Portuguese (Br)",     new Map([["lang_code", "pt_BR"],
                                   ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Portuguese",          new Map([["lang_code", "pt_PT"],
  			           ["utf8", ".UTF-8"],
                                   ["none_utf8", "@euro"]])],
  ["Punjabi",             new Map([["lang_code", "pa_IN"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Romanian",            new Map([["lang_code", "ro_RO"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Russian", 	          new Map([["lang_code", "ru_RU"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Serbian",	          new Map([["lang_code", "sr_RS"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],   
  ["Sinhala", 		  new Map([["lang_code", "si_LK"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Slovak",              new Map([["lang_code", "sk_SK"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Slovenian", 	  new Map([["lang_code", "sl_SI"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Spanish",             new Map([["lang_code", "es_ES"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", "@euro"]])],
  ["Swedish",             new Map([["lang_code", "sv_SE"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Tajik",               new Map([["lang_code", "tg_TJ"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Tamil", 		  new Map([["lang_code", "ta_IN"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Thai",                new Map([["lang_code", "th_TH"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Turkish", 		  new Map([["lang_code", "tr_TR"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Ukrainian", 	  new Map([["lang_code", "uk_UA"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Vietnamese",          new Map([["lang_code", "vi_VN"],
  			           ["utf8", ".UTF-8"],
      				   ["none_utf8", ""]])],
  ["Walloon", 	          new Map([["lang_code", "wa_BE"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", "@euro"]])],
  ["Welsh", 		  new Map([["lang_code", "cy_GB"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Xhosa", 		  new Map([["lang_code", "xh_ZA"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])],
  ["Zulu", 		  new Map([["lang_code", "zu_ZA"],
  			           ["utf8", ".UTF-8"],
				   ["none_utf8", ""]])]
]);


export default {

  availableLanguages: () => {
    return Array.from(languages.entries()).map(e=>e[0])
  },

  langConde: (language) => {
    console.log(languages.get(language).get("lang_code"))  
  },
  
  utf8Encoding: (language) => {
    console.log(languages.get(language).get("utf8"))
  },

  noneUtf8Encoding: (language) => {
    console.log(languages.get(language).get("none_utf8"))
  },
};  